version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no diretório /app do container.
      # Isso permite o live-reload do código e persiste o arquivo do banco de dados SQLite.
      - .:/app